from __future__ import annotations

from dataclasses import dataclass
import json
from typing import Any, Mapping, Sequence

from .execution import load_test_cases
from .llm import LLMBackend, ModelInfo
from .problems import ProblemDocument
from .types import TestCase

__test__ = False

VALID_TEST_MODES = ("bundled", "llm", "both")


class TestGenerationError(RuntimeError):
    """Raised when structured LLM test generation cannot be normalized."""


@dataclass(slots=True, frozen=True)
class GeneratedTestCase:
    """Structured extra test case generated by an LLM backend."""

    name: str
    input: dict[str, Any]
    expected: Any
    validator: str
    source: str = "llm"
    rationale: str = ""

    def to_test_case(self) -> TestCase:
        return TestCase(
            name=self.name,
            input=dict(self.input),
            expected=self.expected,
            validator=self.validator,
            source=self.source,
        )


@dataclass(slots=True, frozen=True)
class TestGenerationResult:
    """Beta metadata for test-generation-aware solve flows."""

    problem_slug: str
    requested_test_mode: str
    effective_test_mode: str
    bundled_test_cases: tuple[TestCase, ...]
    generated_test_cases: tuple[GeneratedTestCase, ...]
    llm_requested: bool
    llm_available: bool
    llm_used: bool
    llm_model_info: ModelInfo | None
    prompt: str | None = None
    raw_payload: Any = None
    warning: str | None = None
    generation_error: str | None = None

    def combined_test_cases(self) -> tuple[TestCase, ...]:
        """Return bundled tests followed by any LLM-generated extras."""

        return self.bundled_test_cases + tuple(
            generated.to_test_case() for generated in self.generated_test_cases
        )

    def to_pipeline_metadata(self) -> dict[str, Any]:
        """Serialize the helper state for later solve-flow/execution use."""

        return {
            "problem_slug": self.problem_slug,
            "requested_test_mode": self.requested_test_mode,
            "effective_test_mode": self.effective_test_mode,
            "bundled_count": len(self.bundled_test_cases),
            "generated_count": len(self.generated_test_cases),
            "generated_cases": [
                {
                    "name": generated.name,
                    "input": generated.input,
                    "expected": generated.expected,
                    "validator": generated.validator,
                    "source": generated.source,
                    "rationale": generated.rationale,
                }
                for generated in self.generated_test_cases
            ],
            "llm_requested": self.llm_requested,
            "llm_available": self.llm_available,
            "llm_used": self.llm_used,
            "llm_model_info": (
                {
                    "name": self.llm_model_info.name,
                    "context_window": self.llm_model_info.context_window,
                    "quantization": self.llm_model_info.quantization,
                    "backend": self.llm_model_info.backend,
                }
                if self.llm_model_info is not None
                else None
            ),
            "warning": self.warning,
            "generation_error": self.generation_error,
        }


def normalize_test_mode(test_mode: str) -> str:
    normalized = test_mode.strip().lower()
    if normalized not in VALID_TEST_MODES:
        raise TestGenerationError(
            f"Unsupported test mode {test_mode!r}. Expected one of: {', '.join(VALID_TEST_MODES)}"
        )
    return normalized


def effective_test_mode(test_mode: str, *, llm_available: bool = True) -> str:
    if test_mode == "bundled":
        return "bundled"
    return test_mode if llm_available else "bundled"


def load_bundled_test_cases(problem: ProblemDocument) -> tuple[TestCase, ...]:
    return tuple(load_test_cases(problem))


def build_test_generation_prompt(
    problem: ProblemDocument,
    bundled_test_cases: Sequence[TestCase],
    *,
    max_generated_cases: int,
) -> str:
    bundled_preview = [
        {
            "name": test_case.name,
            "input": test_case.input,
            "expected": test_case.expected,
            "validator": test_case.validator,
            "source": test_case.source,
        }
        for test_case in bundled_test_cases
    ]
    return (
        "You are lcgrade's test generator.\n"
        "Return only JSON.\n"
        f"Generate up to {max_generated_cases} additional edge-case test cases for this problem.\n"
        "Avoid duplicating any bundled cases already listed below.\n\n"
        f"Slug: {problem.slug}\n"
        f"Title: {problem.metadata.title}\n"
        f"Function: {problem.metadata.function_name}\n"
        f"Validator: {problem.metadata.validator}\n"
        f"Bundled tests: {json.dumps(bundled_preview, ensure_ascii=False, sort_keys=True)}\n\n"
        "Return a JSON object with this shape:\n"
        '{"test_cases":[{"name":"llm-1","input":{},"expected":null,"validator":"exact_match","source":"llm","rationale":"..."}],'
        '"notes":"short optional summary"}\n'
    )


def generate_test_generation(
    problem: ProblemDocument,
    *,
    requested_test_mode: str = "both",
    llm: LLMBackend | None = None,
    bundled_test_cases: Sequence[TestCase] | None = None,
    max_generated_cases: int = 3,
) -> TestGenerationResult:
    normalized = normalize_test_mode(requested_test_mode)
    bundled = tuple(bundled_test_cases) if bundled_test_cases is not None else load_bundled_test_cases(problem)

    llm_requested = normalized in {"llm", "both"}
    if not llm_requested:
        return TestGenerationResult(
            problem_slug=problem.slug,
            requested_test_mode=normalized,
            effective_test_mode=effective_test_mode(normalized),
            bundled_test_cases=bundled,
            generated_test_cases=(),
            llm_requested=False,
            llm_available=False,
            llm_used=False,
            llm_model_info=None,
        )

    if llm is None or not llm.available():
        warning = "LLM backend unavailable; using bundled tests only."
        if llm is not None:
            reason = llm.unavailable_reason()
            if reason:
                warning = f"{reason} Using bundled tests only."
        return TestGenerationResult(
            problem_slug=problem.slug,
            requested_test_mode=normalized,
            effective_test_mode=effective_test_mode(normalized, llm_available=False),
            bundled_test_cases=bundled,
            generated_test_cases=(),
            llm_requested=True,
            llm_available=False,
            llm_used=False,
            llm_model_info=None,
            warning=warning,
        )

    prompt = build_test_generation_prompt(
        problem,
        bundled,
        max_generated_cases=max_generated_cases,
    )
    llm_model_info = llm.model_info()
    try:
        payload = llm.generate_json(
            prompt,
            system_prompt="You are a structured test-case generator for lcgrade.",
            temperature=0.2,
            max_tokens=1024,
        )
        generated = tuple(
            _normalize_generated_case(item, index, default_validator=problem.metadata.validator)
            for index, item in enumerate(_extract_case_payloads(payload), start=1)
        )
        generated = _dedupe_generated_cases(bundled, generated)
        return TestGenerationResult(
            problem_slug=problem.slug,
            requested_test_mode=normalized,
            effective_test_mode=effective_test_mode(normalized, llm_available=True),
            bundled_test_cases=bundled,
            generated_test_cases=generated,
            llm_requested=True,
            llm_available=True,
            llm_used=True,
            llm_model_info=llm_model_info,
            prompt=prompt,
            raw_payload=payload,
        )
    except Exception as exc:
        return TestGenerationResult(
            problem_slug=problem.slug,
            requested_test_mode=normalized,
            effective_test_mode=effective_test_mode(normalized, llm_available=False),
            bundled_test_cases=bundled,
            generated_test_cases=(),
            llm_requested=True,
            llm_available=True,
            llm_used=False,
            llm_model_info=llm_model_info,
            prompt=prompt,
            raw_payload=None,
            warning="LLM test generation failed; using bundled tests only.",
            generation_error=str(exc),
        )


def _extract_case_payloads(payload: Any) -> Sequence[Mapping[str, Any]]:
    if isinstance(payload, Mapping):
        cases = payload.get("test_cases")
        if cases is None:
            cases = payload.get("cases")
        if cases is None:
            cases = payload.get("generated_tests")
        if cases is None:
            return ()
        if not isinstance(cases, Sequence) or isinstance(cases, (str, bytes)):
            raise TestGenerationError("LLM test payload must contain a list of test cases.")
        normalized_cases: list[Mapping[str, Any]] = []
        for case in cases:
            if not isinstance(case, Mapping):
                raise TestGenerationError("Each generated test case must be a mapping.")
            normalized_cases.append(case)
        return tuple(normalized_cases)

    if isinstance(payload, Sequence) and not isinstance(payload, (str, bytes)):
        normalized_cases = []
        for case in payload:
            if not isinstance(case, Mapping):
                raise TestGenerationError("Each generated test case must be a mapping.")
            normalized_cases.append(case)
        return tuple(normalized_cases)

    raise TestGenerationError("LLM test payload must be a JSON object or array of test cases.")


def _normalize_generated_case(
    item: Mapping[str, Any],
    index: int,
    *,
    default_validator: str,
) -> GeneratedTestCase:
    if "input" not in item:
        raise TestGenerationError("Each generated test case must include an input mapping.")
    if not isinstance(item["input"], Mapping):
        raise TestGenerationError("Generated test case input must be a mapping.")

    name = str(item.get("name") or f"llm-{index}")
    expected = item.get("expected")
    validator = str(item.get("validator") or default_validator)
    source = str(item.get("source") or "llm")
    rationale = str(item.get("rationale") or "")
    return GeneratedTestCase(
        name=name,
        input=dict(item["input"]),
        expected=expected,
        validator=validator,
        source=source,
        rationale=rationale,
    )


def _dedupe_generated_cases(
    bundled_test_cases: Sequence[TestCase],
    generated_test_cases: Sequence[GeneratedTestCase],
) -> tuple[GeneratedTestCase, ...]:
    seen = {
        json.dumps(
            {
                "input": test_case.input,
                "expected": test_case.expected,
                "validator": test_case.validator,
            },
            sort_keys=True,
            default=str,
        )
        for test_case in bundled_test_cases
    }

    deduped: list[GeneratedTestCase] = []
    for generated in generated_test_cases:
        signature = json.dumps(
            {
                "input": generated.input,
                "expected": generated.expected,
                "validator": generated.validator,
            },
            sort_keys=True,
            default=str,
        )
        if signature in seen:
            continue
        seen.add(signature)
        deduped.append(generated)
    return tuple(deduped)
